<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="Alex Ayala" />
    
    <link rel="shortcut icon" type="image/x-icon" href="/img/favicon.ico">
    <title>Project 1</title>
    <meta name="generator" content="Hugo 0.83.1" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="/css/main.css" />
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:200,400,200bold,400old" />
    
    <!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
			<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->

    
  </head>

  <body>
    <div id="wrap">
      
      <nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="/"><i class="fa fa-home"></i></a>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="navbar-collapse collapse" id="navbar">
      <ul class="nav navbar-nav navbar-right">
      
        
        <li><a href="/post/">BLOG</a></li>
        
        <li><a href="/projects/">PROJECTS</a></li>
        
        <li><a href="/resume/">RESUME</a></li>
        
      
      </ul>
    </div>
  </div>
</nav>

      <div class="container">
        <div class="blog-post">
          <h3>
            <strong><a href="/project/project1/">Project 1</a></strong>
          </h3>
        </div>
 
<div class="blog-title">
          <h4>
         January 1, 0001 
            &nbsp;&nbsp;
            
          </h4>
        </div>

        <div class="panel panel-default">
          <div class="panel-body">
            <div class="blogpost">
              
<script src="/rmarkdown-libs/header-attrs/header-attrs.js"></script>


<p>This is an R Markdown document. Markdown is a simple formatting syntax for authoring HTML, PDF, and MS Word documents. For more details on using R Markdown see <a href="http://rmarkdown.rstudio.com" class="uri">http://rmarkdown.rstudio.com</a>.</p>
<p>When you click the <strong>Knit</strong> button a document will be generated that includes both content as well as the output of any embedded R code chunks within the document. You can embed an R code chunk like this:</p>
<div id="introduction" class="section level3">
<h3>0. (Introduction)</h3>
<pre class="r"><code>library(plyr)
base1 &lt;- baseball
library(tidyverse)
library(fivethirtyeight)
library(cluster)
library(plotly)
base2 &lt;- mlb_as_play_talent
head(base1)</code></pre>
<pre><code>##           id year stint team lg  g  ab  r  h X2b X3b hr rbi sb cs bb so ibb hbp
## 4  ansonca01 1871     1  RC1    25 120 29 39  11   3  0  16  6  2  2  1  NA  NA
## 44 forceda01 1871     1  WS3    32 162 45 45   9   4  0  29  8  0  4  0  NA  NA
## 68 mathebo01 1871     1  FW1    19  89 15 24   3   1  0  10  2  1  2  0  NA  NA
## 99 startjo01 1871     1  NY2    33 161 35 58   5   1  1  34  4  2  3  0  NA  NA
##    sh sf gidp
## 4  NA NA   NA
## 44 NA NA   NA
## 68 NA NA   NA
## 99 NA NA   NA
##  [ reached &#39;max&#39; / getOption(&quot;max.print&quot;) -- omitted 2 rows ]</code></pre>
<pre class="r"><code>head(base2)</code></pre>
<pre><code>## # A tibble: 6 x 15
##   bbref_id yearid gamenum gameid lgid  startingpos off600 def600 pitch200 asg_pa
##   &lt;chr&gt;     &lt;int&gt;   &lt;int&gt; &lt;chr&gt;  &lt;chr&gt; &lt;chr&gt;        &lt;dbl&gt;  &lt;dbl&gt;    &lt;dbl&gt;  &lt;int&gt;
## 1 goldspa~   2015       0 NLS20~ NL    3             36.8 -0.117      0        3
## 2 mccutan~   2015       0 NLS20~ NL    8             33.7 -0.169      0        3
## 3 harpebr~   2015       0 NLS20~ NL    9             30.9  1.38       0        3
## 4 greinza~   2015       0 NLS20~ NL    1              0    0         15.6      0
## 5 poseybu~   2015       0 NLS20~ NL    2             21.7  7.60       0        2
## 6 frazito~   2015       0 NLS20~ NL    5             14.5  4.79       0        3
## # ... with 5 more variables: asg_ip &lt;dbl&gt;, offper9innasg &lt;dbl&gt;,
## #   defper9innasg &lt;dbl&gt;, pitper9innasg &lt;dbl&gt;, totper9innasg &lt;dbl&gt;</code></pre>
<p><em>The base1 dataset contains all batting statistics for players from 1871 to 2007. Only players with at least 15 seasons of play are included. </em></p>
<p><em>The base2 dataset includes players who made the All Star Games from in 1933 to 2007. This dataset contains performance in the Allstar game along with estimations of talent based off of season performances. </em></p>
<p><em>Both of these datasets originate from <a href="https://baseball-reference.com" class="uri">https://baseball-reference.com</a> which is the main source of baseball statistics for major media organizations. Some of the associations I expect to find is better overall talent in the American League based on my own personal biases. I also expect to see higher numbers in most batting as the years progress since most major sports have experienced a talent creep.</em></p>
</div>
<div id="tidying" class="section level3">
<h3>1. (Tidying)</h3>
<p><em>pivot_longer is used in correlation heatmap and gather is used in wrangling</em></p>
</div>
<div id="joining" class="section level3">
<h3>2. (Joining)</h3>
<pre class="r"><code>base2 &lt;- rename(base2, &#39;id&#39; = bbref_id)
base1 &lt;- rename(base1, &#39;yearid&#39; = year)
fulldata &lt;- left_join(base1, base2, by = c(id=&quot;id&quot;, yearid = &quot;yearid&quot;))
shortdat &lt;- fulldata %&gt;% filter(yearid &gt; 1954, yearid &lt; 2000) %&gt;% filter(!is.na(hbp))  %&gt;% mutate(startingpos = na_if(startingpos, &quot;NULL&quot;)) %&gt;% select(-gamenum, -asg_pa, -asg_ip, -offper9innasg, -defper9innasg, -pitper9innasg, -totper9innasg, -gameid, -stint) %&gt;% distinct()</code></pre>
<p><em>The base1 dataset began with 21699 observations and base2 began with 3930 observations. I used an left_join to ensure we are only analyzing players who have batting stats. We begin with 21799 observations. </em></p>
<p><em>We also filtered for players who played after 1954, since that is the year there was a change to how statistics were recorded. We then filtered by the NA’s in hbp in order to remove incomplete cases without removing players who were not in the all star games. I also removed any entries after 2000. This is because the base1 dataset only contains players who have played at least 15 seasons. So the years after 2000 are incomplete and will retroactively have data added to it as players reach their 15 year mark.</em></p>
<p><em>This left us with 12637 observations. I then removed stats that were specific to the All star game appearance, since we are more interested in the players performance over the season. Then we removed duplicate observations that were from years with multiple all star games. We finally arrive at 12569 observations.</em></p>
<p><em>By not including statistics before 1955 it can be argued that you are not getting the complete picture of the MLB’s history. But in 1955 there were many rule changes that greatly impacted the statistics for players. For examples Sacrifice hits (bunts), were not differentiated from normal swings. Before 1955 there were different standards which is why I chose to exclude them.</em></p>
</div>
<div id="wrangling" class="section level3">
<h3>3. (Wrangling)</h3>
<pre class="r"><code>shortdat &lt;- shortdat  %&gt;%  mutate(talent = off600 + def600 + pitch200) %&gt;% mutate(startingpos = recode(startingpos, &#39;1&#39;=&quot;Pitcher&quot;, &#39;2&#39; = &quot;Catcher&quot;, &#39;3&#39;=&quot;1st Base&quot;, &#39;4&#39;=&quot;2nd Base&quot;, &#39;5&#39;=&quot;3rd Base&quot;, &#39;6&#39;=&quot;Shortstop&quot;, &#39;7&#39;=&quot;Left Field&quot;, &#39;8&#39;=&quot;Center Field&quot;, &#39;9&#39;=&quot;Right Field&quot;, &#39;10&#39;=&quot;Designated Hitter&quot;)) %&gt;% mutate(Allstar = !is.na(talent)) %&gt;% mutate(startingpos = if_else(is.na(startingpos), if_else(off600 == 0, &quot;Backup Pitcher&quot;, &quot;Backup Fielder&quot;), startingpos)) 


#talent grouped by position
shortdat %&gt;% filter(!is.na(talent)) %&gt;% group_by(startingpos) %&gt;% mutate(startingpos = replace_na(startingpos, &quot;Backup&quot;)) %&gt;% mutate(startingpos=factor(startingpos, levels=c(&quot;Pitcher&quot;, &quot;Backup Pitcher&quot;, &quot;Catcher&quot;, &quot;1st Base&quot;, &quot;2nd Base&quot;, &quot;3rd Base&quot;, &quot;Shortstop&quot;, &quot;Left Field&quot;, &quot;Center Field&quot;, &quot;Right Field&quot;, &quot;Designated Hitter&quot;, &quot;Backup Fielder&quot;))) %&gt;% summarize(avg_talent = mean(talent), sd_talent = sd(talent), var_talent = var(talent), min_talent = min(talent), max_talent = max(talent))</code></pre>
<pre><code>## # A tibble: 12 x 6
##    startingpos       avg_talent sd_talent var_talent min_talent max_talent
##    &lt;fct&gt;                  &lt;dbl&gt;     &lt;dbl&gt;      &lt;dbl&gt;      &lt;dbl&gt;      &lt;dbl&gt;
##  1 Pitcher                 9.66      7.11       50.5     -2.27        31.1
##  2 Backup Pitcher          7.82      6.17       38.0     -9.88        29.4
##  3 Catcher                19.5      11.9       142.      -8.81        45.6
##  4 1st Base               15.6      12.3       150.     -20.4         41.7
##  5 2nd Base               17.7      14.8       219.     -12.0         57.6
##  6 3rd Base               21.1      13.8       192.      -6.32        47.6
##  7 Shortstop              16.2      13.9       193.     -11.9         48.6
##  8 Left Field             22.9      15.6       242.      -8.82        56.2
##  9 Center Field           31.0      14.9       222.       0.289       70.5
## 10 Right Field            20.3      13.3       176.     -18.5         48.8
## 11 Designated Hitter      14.8      12.5       156.      -2.72        37.5
## 12 Backup Fielder         12.9      12.9       166.     -24.7         54.1</code></pre>
<p><em>To find the summary statistics, I grouped the data by the player’s position. The players who did not have a position listed, were categorized as either backup picthers or backup hitters. The talent statistic is an estimation of both offensive and defensive talent, in runs above league average. The Center Field talent levels is skewed higher due to the dominance of center fielder Mickey Mantle compared to his contemporaries.</em></p>
<pre class="r"><code>#offensive talent by League
shortdat %&gt;%  filter(!is.na(talent)) %&gt;% group_by(lgid) %&gt;% summarize(avg_off600 = mean(off600), sd_off600 = sd(off600), var_off600 = var(off600), min_off600 = min(off600), max_off600 = max(off600))</code></pre>
<pre><code>## # A tibble: 2 x 6
##   lgid  avg_off600 sd_off600 var_off600 min_off600 max_off600
##   &lt;chr&gt;      &lt;dbl&gt;     &lt;dbl&gt;      &lt;dbl&gt;      &lt;dbl&gt;      &lt;dbl&gt;
## 1 AL          11.4      13.9       194.      -25.7       68.7
## 2 NL          12.4      14.4       207.      -19.4       52.0</code></pre>
<p><em>These statistics shows that offensive talent is more plentiful in the American League</em></p>
<pre class="r"><code>#RBI leaderboards 
shortdat %&gt;% group_by(rbi, id) %&gt;% count(sort=T) %&gt;% ungroup() %&gt;% arrange(desc(rbi)) </code></pre>
<pre><code>## # A tibble: 8,302 x 3
##      rbi id            n
##    &lt;int&gt; &lt;chr&gt;     &lt;int&gt;
##  1   165 ramirma02     1
##  2   158 sosasa01      1
##  3   157 gonzaju03     1
##  4   153 davisto02     1
##  5   150 galaran01     1
##  6   149 fostege01     1
##  7   148 benchjo01     1
##  8   148 palmera01     1
##  9   147 mcgwima01     2
## 10   147 griffke02     1
## # ... with 8,292 more rows</code></pre>
<p><em>Here we have the RBI leaderboards and their respective player ID. Mark Mcgwire is in a 3 way tie for 9th with Ken Griffey and himself! He had two seperate seasons where he had 147 RBI’s</em></p>
<pre class="r"><code>#Summary statistics of multiple variables
shortdat %&gt;% summarize_at(vars(ab, r, h, so, sb, sh, bb, hbp), funs(mean, sd, var, median, max)) %&gt;% gather(key = &quot;key&quot;, value = &quot;value&quot;) %&gt;% separate(key, c(&quot;variable&quot;, &quot;stat&quot;), sep = &quot;_&quot;) %&gt;% spread(stat, value) %&gt;% mutate(variable = recode(variable, &#39;ab&#39;=&quot;At Bats&quot;, &#39;bb&#39; = &quot;Walks&quot;, &#39;h&#39;=&quot;Hits&quot;, &#39;r&#39;=&quot;Runs&quot;, &#39;sb&#39;=&quot;Stolen Bases&quot;, &#39;sh&#39;=&quot;Bunts&quot;, &#39;so&#39;=&quot;Strike Outs&quot;, &#39;hbp&#39; = &quot;Hit by Pitch&quot;))</code></pre>
<pre><code>##       variable max       mean median         sd          var
## 1      At Bats 705 212.947410     99 219.791150 48308.149446
## 2        Walks 162  21.897287      8  27.087395   733.726957
## 3         Hits 240  57.163657     23  63.271638  4003.300156
## 4 Hit by Pitch  35   1.348397      0   2.399265     5.756474
## 5         Runs 146  28.798870     11  33.784308  1141.379499
## 6 Stolen Bases 130   4.335667      0   9.581582    91.806717
## 7        Bunts  40   2.162781      1   3.249626    10.560069
## 8  Strike Outs 189  32.857586     22  34.356764  1180.387260</code></pre>
<p><em>Summary statistics for various batting statistics. Variability is so high for at bats, since most pitchers do not step up to bat anymore.</em></p>
</div>
<div id="visualizing" class="section level3">
<h3>4. (Visualizing)</h3>
<pre class="r"><code>#Average HRs by League
shortdat %&gt;% filter(hr &gt; 0) %&gt;% ggplot(aes(yearid, hr)) + geom_bar(stat=&quot;summary&quot;, fun=mean, fill=&quot;Light Blue&quot;, color = &quot;black&quot;) + scale_x_continuous(name=&quot;Year&quot;) + scale_y_continuous(name=&quot;Average Homeruns&quot;, breaks=seq(0, 15, 2.5)) + facet_wrap(~lg) + ggtitle(&quot;Average Homeruns Hit by Each League&quot;) + theme_minimal()</code></pre>
<p><img src="/project/project1_files/figure-html/unnamed-chunk-7-1.png" width="672" style="display: block; margin: auto;" />
<em>In the few years before this data was collected, the average homeruns was increasing. Note: The dip in 1981 was due to the player’s strike that led to a cancellation of 713 games.</em></p>
<pre class="r"><code>#correlation heatmap
shortdat %&gt;% filter(Allstar == TRUE) %&gt;% select_if(is.numeric) %&gt;% select(off600, pitch200, r, h, hr, rbi, so, sh, bb, hbp) %&gt;% cor %&gt;% as.data.frame %&gt;% rownames_to_column  %&gt;% pivot_longer(-1) %&gt;% ggplot(aes(rowname,name,fill=value))+geom_tile() + geom_text(aes(label=round(value,2))) + xlab(&quot;&quot;)+ylab(&quot;&quot;)+coord_fixed() + scale_fill_gradient2(low = &quot;pink&quot;, mid=&quot;white&quot;,high=&quot;blue&quot;) + scale_y_discrete(labels=c(&quot;Walks(bb)&quot;,&quot;Hits (h)&quot;,&quot;Hit by Pitch (hbp)&quot;, &quot;Home Runs (hr)&quot;, &quot;Offensive Talent (off600)&quot;,&quot;Pitching talent (pitch200)&quot;,&quot;Runs (r)&quot;,&quot;Runs Batted In (rbi)&quot;, &quot;Bunts (sh)&quot;, &quot;Strike Outs (so)&quot;)) + ggtitle(&quot;Correlation Heatmap of Batting Stats for All Stars&quot;)</code></pre>
<p><img src="/project/project1_files/figure-html/unnamed-chunk-8-1.png" width="672" style="display: block; margin: auto;" /></p>
<p><em>Here you can see just poorly pitching is correlated with batting statistics. The only exception is bunting.</em></p>
<pre class="r"><code>shortdat %&gt;% ggplot(aes(yearid, h, color = Allstar)) + geom_point(stat=&#39;summary&#39;, fun=mean) + ggtitle(&quot;Baseball&quot;) + xlab(&quot;year&quot;) + ylab(&quot;Average hits&quot;) + geom_smooth(method=&#39;lm&#39;,aes(color=Allstar)) + ggtitle(&quot;Average Hits of All Stars and non All Stars&quot;) + theme_classic()</code></pre>
<p><img src="/project/project1_files/figure-html/unnamed-chunk-9-1.png" width="672" style="display: block; margin: auto;" />
<em>This table shows that on average, an all star caliber player hits the ball 3 more times than the rest of the league.</em></p>
</div>
<div id="dimensionality-reduction" class="section level3">
<h3>5. (Dimensionality Reduction)</h3>
<pre class="r"><code>clust_dat &lt;- shortdat  %&gt;% select(g, ab, r, h, X2b, X3b, hr, rbi, sb, cs, hbp, sh, sf, gidp, talent, Allstar) %&gt;% pam(4)
set.seed(348)
final &lt;-  shortdat %&gt;% mutate(cluster=clust_dat$clustering) %&gt;% sample_n(500)
ggplot(final, aes(x=g,y=rbi, color=cluster, shape = Allstar))+geom_point() + xlab(&quot;Games&quot;) + ylab(&quot;Runs Batted In&quot;) + theme_light()</code></pre>
<p><img src="/project/project1_files/figure-html/unnamed-chunk-10-1.png" width="672" style="display: block; margin: auto;" />
<em>While it would be neat to have all the players clustered by their position, there is simply too much overlap to feasibly do that. The 4 clusters are likely pitchers (many games played with low batting), poor battesr, average batters, and the elite. You can see that most of the all stars have a high amount of runs batted in. If you are not a pitcher, it seems a high amount of RBI’s are almost a requirement to become an all star.</em></p>
</div>

            
        <hr>         <div class="related-posts">
                <h5>Related Posts</h5>
                
              </div> 
            </div>
          </div>

   <hr>  <div class="disqus">
  <div id="disqus_thread"></div>
  <script type="text/javascript">

    (function() {
      
      
      if (window.location.hostname == "localhost")
        return;

      var disqus_shortname = '';
      var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
      dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
      (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
  </script>
  <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
  <a href="http://disqus.com/" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
</div> 
        </div>
      </div>
    </div>

    
    <footer>
  <div id="footer">
    <div class="container">
      <p class="text-muted">&copy; All rights reserved. Powered by <a href="https://gohugo.io/">Hugo</a> and
      <a href="http://www.github.com/nurlansu/hugo-sustain/">sustain</a> with ♥</p>
    </div>
  </div>
</footer>
<div class="footer"></div>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="/js/docs.min.js"></script>
<script src="/js/main.js"></script>

<script src="/js/ie10-viewport-bug-workaround.js"></script>


    
  </body>
</html>
